package project;

import konek.koneksi;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import konek.koneksi;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.text.SimpleDateFormat;
import static project.pinjaman.cn;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class DataBuku extends javax.swing.JFrame {

    /**
     * Creates new form DataBuku
     */
    public DataBuku() {
        initComponents();
        txtcari.setBackground(new Color(0,0,0,0));
        txtcari.setBorder(null);
        datatable();
        cmbkategori.setBackground(new Color(0,0,0,0));
        setExtendedState(DataBuku.MAXIMIZED_BOTH);
    }
    public static Connection cn;
    public static ResultSet rs;
    public static Statement st;
    private void datatable() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("kode buku");
        tbl.addColumn("judul buku");
        tbl.addColumn("pengarang");
        tbl.addColumn("penerbit");
        tbl.addColumn("tahun terbit");
        tbl.addColumn("kategori");
        tbl.addColumn("jumlah");
        table.setModel(tbl);
        try{
            Statement statement = (Statement)koneksi.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM data_buku");

            while (res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("kode_buku"),
                    res.getString("judul_buku"),
                    res.getString("pengarang"),
                    res.getString("penerbit"),
                    res.getString("tahun_terbit"),
                    res.getString("kategori"),
                    res.getString("jumlah")
                });
                table.setModel(tbl);
            }
        }catch (SQLException e){
                    JOptionPane.showMessageDialog(rootPane, "salah"+e.getMessage() );
     }     
        }
private void cari() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("kode buku");
        tbl.addColumn("judul buku");
        tbl.addColumn("pengarang");
        tbl.addColumn("penerbit");
        tbl.addColumn("tahun terbit");
        tbl.addColumn("kategori");
        tbl.addColumn("jumlah");
        table.setModel(tbl);
        try {
            cn = koneksi.GetConnection();
            st = cn.createStatement();

            // Update tabel
            rs = st.executeQuery("SELECT *FROM data_buku WHERE kode_buku = '" + txtcari.getText()+"'");
            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("kode_buku"),
                    rs.getString("judul_buku"),
                    rs.getString("pengarang"),
                    rs.getString("penerbit"),
                    rs.getString("tahun_terbit"),
                    rs.getString("kategori"),
                    rs.getString("jumlah"),
                   });
                table.setModel(tbl);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtpengarang = new javax.swing.JTextField();
        txtpenerbit = new javax.swing.JTextField();
        txtkodebuku = new javax.swing.JTextField();
        txttahun = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txtkategori = new javax.swing.JTextField();
        txtjudulbuku = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        cmbkategori = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "KODE BUKU", "JUDUL BUKU", "PENGARANG", "PENERBIT", "TAHUN TERBIT", "KATEBORI", "JUMLAH"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 1070, 680));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kode Buku");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 530, -1, 30));
        getContentPane().add(txtpengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 610, 210, 30));
        getContentPane().add(txtpenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 650, 210, 30));
        getContentPane().add(txtkodebuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 530, 210, 30));

        txttahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttahunActionPerformed(evt);
            }
        });
        getContentPane().add(txttahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 690, 210, 30));
        getContentPane().add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 770, 210, 30));

        txtkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkategoriActionPerformed(evt);
            }
        });
        getContentPane().add(txtkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 730, 210, 30));
        getContentPane().add(txtjudulbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 570, 210, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Kategori");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 730, -1, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Penerbit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 650, 80, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Jumlah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 770, 70, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tahun Terbit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 690, -1, 30));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Judul Buku");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 570, 110, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Pengarang");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 610, 100, 30));

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 180, 330, 40));

        cmbkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbkategori.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cmbkategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 180, 190, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnbuku+.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1930, 310, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnbuku-.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 1030, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnbukuedt.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 1020, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnpinjaman.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnusername.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnabsensi.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btndatabuku.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnbuku+.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 1020, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/databuku.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttahunActionPerformed

    private void txtkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkategoriActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
      int bar = table.getSelectedRow();
        String a = table.getValueAt(bar, 0).toString();
        String b = table.getValueAt(bar, 1).toString();
        String c = table.getValueAt(bar, 2).toString();
        String d = table.getValueAt(bar, 4).toString();
        String e = table.getValueAt(bar, 5).toString();
        String f = table.getValueAt(bar, 6).toString();
       

        txtkodebuku.setText(a);
        txtjudulbuku.setText(b);
        txtpengarang.setText(c);
         txtpenerbit.setText(d);
        txttahun.setText(e);
        txtkategori.setText(f);
        
    }//GEN-LAST:event_tableMouseClicked

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        String kodebuku = txtkodebuku.getText();
        String judulbuku = txtjudulbuku.getText();
        String pengarang = txtpengarang.getText();
        String penerbit = txtpenerbit.getText();
        String tahunterbit = txttahun.getText();
        String kategori = txtkategori.getText();
        String jumlah = txtjumlah.getText();

        try {
            // Connect
            String sql = "INSERT INTO `data_buku`(kode_buku, judul_buku, pengarang, penerbit, tahun_terbit, kategori, jumlah ) VALUES (?, ?, ?, ?, ?, ?, ?)";
            cn = koneksi.GetConnection();
            PreparedStatement pst = cn.prepareStatement(sql);

            // Set paramater
            pst.setString(1, kodebuku);
            pst.setString(2, judulbuku);
            pst.setString(3, pengarang);
            pst.setString(4, penerbit);
            pst.setString(5, tahunterbit);
            pst.setString(6, kategori);
            pst.setString(7, jumlah);

            // Execute
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data tersimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
        }
        // Update table
        datatable();
                      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        String kodebuku = txtkodebuku.getText();
        String judulbuku = txtjudulbuku.getText();
        String pengarang = txtpengarang.getText();
        String penerbit = txtpenerbit.getText();
        String tahun = txttahun.getText();
        String kategori = txtkategori.getText();
        String jumlah = txtjumlah.getText();
        try {
            // Connect
            String sql =( "UPDATE data_buku SET judul_buku= ?,pengarang=?,penerbit= ?,tahun_terbit= ?,kategori= ?,jumlah= ? WHERE kode_buku=?");
            cn = koneksi.GetConnection();
            PreparedStatement pst = cn.prepareStatement(sql);

            // Set paramater
            pst.setString(1, judulbuku);
            pst.setString(2, pengarang);
            pst.setString(3, penerbit);
            pst.setString(4, tahun);
            pst.setString(5, kategori);
            pst.setString(6, jumlah);
            pst.setString(7,kodebuku);

            // Execute
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil diedit");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
        }
        // Update table
        datatable();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        int row = table.getSelectedRow();

        if (row < 0) {
            // Error if row not selected
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus");
            return;
        }

        // get value from first row
        String databuku = table.getValueAt(row, 0).toString();
        try {
            String sql = "DELETE FROM  data_buku WHERE kode_buku = ?";
            cn = koneksi.GetConnection();
            PreparedStatement pst = cn.prepareStatement(sql);
            pst = cn.prepareStatement(sql);
            pst.setString(1, databuku);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus" + e.getMessage());
        }
        datatable();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
new DataBuku().show();
                dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
new pinjaman().show();
                dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        String kodebuku = txtkodebuku.getText();
        String judulbuku = txtjudulbuku.getText();
        String pengarang = txtpengarang.getText();
        String penerbit = txtpenerbit.getText();
        String tahunterbit = txttahun.getText();
        String kategori = txtkategori.getText();
        String jumlah = txtjumlah.getText();
        

        try {
            // Connect
            String sql = "INSERT INTO `data_buku`(kode_buku,judul_buku, pengarang, penerbit, tahun_terbit, kategori, jumlah) VALUES (?, ?, ?, ?, ?, ?, ?)";
            cn = koneksi.GetConnection();
            PreparedStatement pst = cn.prepareStatement(sql);

            // Set paramater
            pst.setString(1, kodebuku);
            pst.setString(2, judulbuku);
            pst.setString(3, pengarang);
            pst.setString(4, penerbit);
            pst.setString(5, tahunterbit);
            pst.setString(6, kategori);
            pst.setString(7, jumlah);

            // Execute
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data tersimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
        }
        // Update table
        datatable();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtjudulbuku;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkategori;
    private javax.swing.JTextField txtkodebuku;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private javax.swing.JTextField txttahun;
    // End of variables declaration//GEN-END:variables
}
