/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.awt.Color;
import konek.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static project.DataBuku.cn;
import static project.login.cn;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ASUS
 */
public class pengembalian extends javax.swing.JFrame {

    /**
     * Creates new form pengembalian
     */
    public pengembalian() {
        initComponents();
        datatable();
    }
public static Connection cn;
    public static ResultSet rs;
    public static Statement st;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtidpinjaman = new javax.swing.JTextField();
        txtidpengembalian = new javax.swing.JTextField();
        txtnis = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtkelas = new javax.swing.JTextField();
        txtkodebuku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnpinjaman.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnusername.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnabsensi.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btndatabuku.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnrefresh.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PENGEMBALIAN", "ID PINJAMAN", "KODE BUKU", "TANGGAL", "NIS SISWA", "NAMA SISWA", "KELAS"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 950, 790));
        getContentPane().add(txtidpinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 530, 150, 30));

        txtidpengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpengembalianActionPerformed(evt);
            }
        });
        getContentPane().add(txtidpengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 492, 150, 30));
        getContentPane().add(txtnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 650, 150, 30));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 690, 150, 30));
        getContentPane().add(txtkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 730, 150, 30));
        getContentPane().add(txtkodebuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 570, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID PENGEMBALIAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 500, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("NAMA SISWA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 700, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("TANGGAL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 620, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("NIS SISWA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 660, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("KODE BUKU");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 580, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("KELAS");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 740, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("ID PINJAMAN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 540, -1, -1));
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 610, 150, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btneditpnjm.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 440, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnhapuspnjm.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 440, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btntambahpnjm.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pengembalian.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidpengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpengembalianActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
      int row = table.getSelectedRow();

        if (row < 0) {
            // Error if row not selected
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus");
            return;
        }

        // get value from first row
        String databuku = table.getValueAt(row, 0).toString();
        try {
            String sql = "DELETE FROM  pengembalian WHERE id_pengembalian = ?";
            cn = koneksi.GetConnection();
            PreparedStatement pst = cn.prepareStatement(sql);
            pst = cn.prepareStatement(sql);
            pst.setString(1, databuku);
            pst.execute();

            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus" + e.getMessage());
        }
        datatable();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String idpengembalian = txtidpengembalian.getText();
        String idpinjaman = txtidpinjaman.getText();
        String kodebuku = txtkodebuku.getText();
        String tanggal = date.format(jdate.getDate());
        String nis = txtnis.getText();
        String nama = txtnama.getText();
        String kelas = txtkelas.getText();
       
        try {
            // Connect
            String sql =( "UPDATE pengembalian SET id_pinjaman= ?,kode_buku=?,tanggal= ?,nis= ?,nama= ?,kelas= ? WHERE id_pengembalian=?");
            cn = koneksi.GetConnection();
            PreparedStatement pst = cn.prepareStatement(sql);

            // Set paramater
            pst.setString(1, idpengembalian);
            pst.setString(1, idpinjaman);
            pst.setString(2, kodebuku);
            pst.setString(3, tanggal);
            pst.setString(4, nis);
            pst.setString(5, nama);
            pst.setString(6, kelas);
            pst.setString(7, idpengembalian);


            // Execute
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil diedit");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
        }
        // Update table
        datatable();          
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String idpengembalian = txtidpengembalian.getText();
        String idpinjaman = txtidpinjaman.getText();
        String kodebuku = txtkodebuku.getText();
        String tanggal = date.format(jdate.getDate());
        String nis = txtnis.getText();
        String nama = txtnama.getText();
        String kelas = txtkelas.getText();

        try {
            // Connect
            String sql = "INSERT INTO `pengembalian`(id_pengembalian, id_pinjaman, kode_buku, tanggal, nis, nama, kelas) VALUES (?, ?, ?, ?, ?, ?, ?)";
            cn = koneksi.GetConnection();
            PreparedStatement pst = cn.prepareStatement(sql);

            // Set paramater
            pst.setString(1, idpengembalian);
            pst.setString(2, idpinjaman);
            pst.setString(3, kodebuku);
            pst.setString(4, tanggal);
            pst.setString(5, nis);
            pst.setString(6, nama);
            pst.setString(7, kelas);

            // Execute
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data tersimpan");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
        }
        // Update table
        datatable();
       
       
       
       
       
               // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
int bar = table.getSelectedRow();
String a = table.getValueAt(bar, 0).toString();
String b = table.getValueAt(bar, 1).toString();
String c = table.getValueAt(bar, 2).toString();
String d = table.getValueAt(bar, 3).toString();
String e = table.getValueAt(bar, 4).toString();
String f = table.getValueAt(bar, 5).toString();
String g = table.getValueAt(bar, 6).toString();

Date date;
try {
    date = dateFormat.parse(d);
} catch (ParseException ex) {
    // Handle parsing exception
    ex.printStackTrace();
    return;
}

txtidpengembalian.setText(a);
txtidpinjaman.setText(b);
txtkodebuku.setText(c);
jdate.setDate(date); // Assuming jdate is a JDatePicker or similar
txtnis.setText(e);
txtnama.setText(f);
txtkelas.setText(g);

    }//GEN-LAST:event_tableMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
new pinjaman().show();
                dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
 new DataBuku().show();
                dispose();        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
new pinjaman().show();
                dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
new Absen().show();
                dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtidpengembalian;
    private javax.swing.JTextField txtidpinjaman;
    private javax.swing.JTextField txtkelas;
    private javax.swing.JTextField txtkodebuku;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnis;
    // End of variables declaration//GEN-END:variables

    private void datatable() {
         DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("id pengembalian");
        tbl.addColumn("id pinjaman");
        tbl.addColumn("kode buku");
        tbl.addColumn("tanggal");
        tbl.addColumn("nis");
        tbl.addColumn("nama");
        tbl.addColumn("kelas");
        table.setModel(tbl);
        try{
            Statement statement = (Statement)koneksi.GetConnection().createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM pengembalian");

            while (res.next())
            {
                tbl.addRow(new Object[]{
                    res.getString("id_pengembalian"),
                    res.getString("id_pinjaman"),
                    res.getString("kode_buku"),
                    res.getString("tanggal"),
                    res.getString("nis"),
                    res.getString("nama"),
                    res.getString("kelas"),
                    
                });
                table.setModel(tbl);
            }
        }catch (SQLException e){
                    JOptionPane.showMessageDialog(rootPane, "salah"+e.getMessage() );
     }
    }
}
